import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const databaseSchema = appSchema({
  version: 8,
  tables: [
    tableSchema({
      name: 'products',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true, isIndexed: true },
        { name: 'inventory', type: 'number', isOptional: true },
        { name: 'enable_variants', type: 'boolean', isOptional: true },
        { name: 'price_in_pkr_enabled', type: 'boolean', isOptional: true },
        { name: 'price_in_pkr', type: 'number', isOptional: true },
        { name: 'cost_in_pkr_enabled', type: 'boolean', isOptional: true },
        { name: 'cost_in_pkr', type: 'number', isOptional: true },
        { name: 'slug', type: 'string', isIndexed: true },
        { name: 'media', type: 'string', isOptional: true },
        { name: 'categories', type: 'string', isOptional: true },
        { name: 'variant_types', type: 'string', isOptional: true },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'variants',
      columns: [
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true, isIndexed: true },
        { name: 'inventory', type: 'number', isOptional: true },
        { name: 'price_in_pkr_enabled', type: 'boolean', isOptional: true },
        { name: 'price_in_pkr', type: 'number', isOptional: true },
        { name: 'cost_in_pkr_enabled', type: 'boolean', isOptional: true },
        { name: 'cost_in_pkr', type: 'number', isOptional: true },
        { name: 'options', type: 'string', isOptional: true },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'payment_method', type: 'string', isIndexed: true },
        { name: 'customer_name', type: 'string' },
        { name: 'customer_phone', type: 'string', isOptional: true },
        { name: 'currency', type: 'string', isOptional: true },
        { name: 'subtotal', type: 'number', isOptional: true },
        { name: 'discount', type: 'number', isOptional: true },
        { name: 'cogs_total', type: 'number', isOptional: true },
        { name: 'gross_profit', type: 'number', isOptional: true },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'purchased_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'order_items',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'variant_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'quantity', type: 'number' },
        { name: 'unit_price_in_pkr', type: 'number', isOptional: true },
        { name: 'unit_cost_in_pkr', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'variant_types',
      columns: [
        { name: 'label', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'variant_options',
      columns: [
        { name: 'variant_type', type: 'string', isIndexed: true },
        { name: 'label', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'media',
      columns: [
        { name: 'alt', type: 'string' },
        { name: 'url', type: 'string' },
        { name: 'file_name', type: 'string', isOptional: true },
        { name: 'mime_type', type: 'string', isOptional: true },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'reports',
      columns: [
        { name: 'daily', type: 'string' },
        { name: 'last_30_days', type: 'string' },
        { name: 'last_7_days', type: 'string' },
        { name: 'today', type: 'string' },
        { name: 'top_products_30d', type: 'string' },
        { name: 'tenant', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});

export default databaseSchema;
